In [1]:
import pandas as pd

context = pd.read_csv(r"C:\Users\ferna\Desktop\Apuntes Clase\Ejercicios python caseros\fitlife_context.csv")
members = pd.read_csv(r"C:\Users\ferna\Desktop\Apuntes Clase\Ejercicios python caseros\fitlife_members.csv")

print(context.head())
print(members.head())

     month  competitor_lowcost_price campaign_active service_incident  \
0  2022-01                      25.0   january_promo              NaN
1  2022-02                      25.0             NaN              NaN
2  2022-03                      25.0             NaN              NaN
3  2022-04                      25.0             NaN              NaN
4  2022-05                      25.0             NaN              NaN

   monthly_fixed_costs  avg_occupancy_rate  acquisition_cost_avg
0                16699                0.55                  54.4
1                16878                0.49                  31.6
2                15846                0.44                  36.0
3                16366                0.38                  39.7
4                16465                0.39                  31.8
  member_id    month     center     plan  price_paid signup_date  \
0     M0001  2022-01  westfield  premium        44.1  2020-07-27
1     M0001  2022-02  westfield  premium        44.1  2020-07-27
2     M0001  2022-03  westfield  premium        44.1  2020-07-27
3     M0001  2022-04  westfield  premium        44.1  2020-07-27
4     M0001  2022-05  westfield  premium        44.1  2020-07-27

  acquisition_channel  tenure_months  visits_this_month  \
0           corporate             18                 19
1           corporate             19                 18
2           corporate             20                 15
3           corporate             21                 21
4           corporate             22                 20

   group_classes_attended  uses_app  has_personal_trainer  cost_to_serve  \
0                       6      True                 False          26.02
1                       4      True                 False          22.39
2                       5      True                 False          21.29
3                       4      True                 False          24.83
4                       5      True                 False          25.45

   status churn_reason
0  active          NaN
1  active          NaN
2  active          NaN
3  active          NaN
4  active          NaN

In [2]:
df = pd.merge(context, members, on="month", how="left")

df.shape
df.columns
df.head()

,month,competitor_lowcost_price,campaign_active,service_incident,monthly_fixed_costs,avg_occupancy_rate,acquisition_cost_avg,member_id,center,plan,...,signup_date,acquisition_channel,tenure_months,visits_this_month,group_classes_attended,uses_app,has_personal_trainer,cost_to_serve,status,churn_reason
0,2022-01,25.0,january_promo,NaN,16699,0.55,54.4,M0001,westfield,premium,...,2020-07-27,corporate,18,19,6,True,False,26.02,active,NaN
1,2022-01,25.0,january_promo,NaN,16699,0.55,54.4,M0002,westfield,family,...,2021-09-21,walk_in,4,5,5,True,True,47.38,active,NaN
2,2022-01,25.0,january_promo,NaN,16699,0.55,54.4,M0003,downtown,basic,...,2021-11-26,walk_in,2,6,4,False,True,32.06,active,NaN
3,2022-01,25.0,january_promo,NaN,16699,0.55,54.4,M0004,westfield,premium,...,2020-09-27,referral,16,14,5,True,False,22.04,active,NaN
4,2022-01,25.0,january_promo,NaN,16699,0.55,54.4,M0005,southgate,premium,...,2021-06-08,digital,7,18,5,True,True,43.90,active,NaN

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16334 entries, 0 to 16333
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   month                     16334 non-null  object
 1   competitor_lowcost_price  16334 non-null  float64
 2   campaign_active           4043 non-null   object
 3   service_incident          1376 non-null   object
 4   monthly_fixed_costs       16334 non-null  int64
 5   avg_occupancy_rate        16334 non-null  float64
 6   acquisition_cost_avg      16334 non-null  float64
 7   member_id                 16334 non-null  object
 8   center                    16334 non-null  object
 9   plan                      16334 non-null  object
 10  price_paid                16334 non-null  float64
 11  signup_date               16334 non-null  object
 12  acquisition_channel       16334 non-null  object
 13  tenure_months             16334 non-null  int64
 14  visits_this_month         16334 non-null  int64
 15  group_classes_attended    16334 non-null  int64
 16  uses_app                  16334 non-null  bool
 17  has_personal_trainer      16334 non-null  bool
 18  cost_to_serve             16334 non-null  float64
 19  status                    16334 non-null  object
 20  churn_reason              411 non-null    object
dtypes: bool(2), float64(5), int64(4), object(10)
memory usage: 2.4+ MB

,competitor_lowcost_price,monthly_fixed_costs,avg_occupancy_rate,acquisition_cost_avg,price_paid,tenure_months,visits_this_month,group_classes_attended,cost_to_serve
count,16334.000000,16334.000000,16334.000000,16334.000000,16334.000000,16334.000000,16334.000000,16334.000000,16334.000000
mean,21.390168,16200.441472,0.402563,35.791692,48.654310,16.638790,9.750031,3.017020,19.301622
std,1.897490,512.070578,0.064889,6.819074,15.132137,12.601151,4.489846,1.972865,11.629268
min,19.000000,15295.000000,0.280000,26.700000,23.200000,0.000000,0.000000,0.000000,1.500000
25%,20.000000,15827.000000,0.360000,30.700000,29.000000,6.000000,7.000000,1.000000,10.810000
50%,21.000000,16211.000000,0.400000,35.000000,49.000000,14.000000,9.000000,3.000000,17.200000
75%,23.000000,16599.000000,0.440000,38.600000,69.000000,25.000000,12.000000,4.000000,23.500000
max,25.000000,17189.000000,0.550000,54.400000,69.000000,59.000000,36.000000,10.000000,60.740000

In [4]:
# Distribución de los clientes por plan
df["plan"].value_counts(normalize=True)
# De los 3 planes parece que el basic no es el principal

plan
premium    0.417901
family     0.307824
basic      0.274275
Name: proportion, dtype: float64

In [5]:
# Ingresos por plan
df.groupby("plan")["price_paid"].sum()
# El basic y el family parecen los que mas ingresos generan para el negocio.

plan
basic      127188.2
family     340363.2
premium    327168.1
Name: price_paid, dtype: float64

In [6]:
# Margen por plan 
df["margin"] = df["price_paid"] - df["cost_to_serve"]
df.groupby("plan")["margin"].mean()
# Esto es ORO analítico. Significa: Basic = menor margen, Family = producto estrella en rentabilidad y Premium = equilibrio volumen + margen

plan
basic      18.909556
family     47.329795
premium    22.964810
Name: margin, dtype: float64